import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/authContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blockwarden Audit Aggregator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
           <div className='flex'>
            <main className='flex-1'>
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
